## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [4]:
data = np.zeros(10)
data[...] = 2.5
data

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [5]:
data = np.zeros(10)
data[4] = 1
data

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [6]:
data = np.arange(10)
data[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [7]:
data = np.arange(9).reshape((3,3))
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [8]:
data = np.array([1, 2, 0, 0, 4, 0])
data.nonzero()[0]

array([0, 1, 4])

Создать 3x3 единичную матрицу

In [9]:
data = np.eye(3, 3)
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создать массив 3x3x3 со случайными значениями

In [10]:
data = np.random.randint(0, 10, size=3*3*3).reshape((3,3,3))
data

array([[[8, 9, 3],
        [8, 7, 7],
        [2, 9, 0]],

       [[6, 1, 4],
        [2, 4, 9],
        [1, 9, 2]],

       [[8, 9, 0],
        [0, 2, 9],
        [3, 5, 9]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [11]:
data = np.random.random(30)
data.mean()

0.5382531625093002

Перемножить матрицы 5x3 и 3x2

In [12]:
matrix1 = np.random.randint(low=0, high=5, size=5*3).reshape((5,3))
matrix2 = np.random.randint(low=0, high=5, size=3*2).reshape((3,2))
np.dot(matrix1, matrix2)

array([[ 2, 18],
       [ 4, 12],
       [14, 32],
       [ 4,  6],
       [12, 30]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [13]:
# 1-ый вариант
np.linspace(0, 1, num=12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [14]:
# 2-ой вариант
np.random.uniform(low=1e-6, high=1, size=10)

array([0.79402718, 0.60413371, 0.80919617, 0.19957055, 0.7024493 ,
       0.35368298, 0.99805359, 0.68223415, 0.70079981, 0.5214417 ])

Заменить максимальный элемент на ноль

In [15]:
data = np.array([5, 4, 4, 3, 3, 3, 2, 2, 1, 111, 1, 2, 2, 3, 3, 3, 4, 4, 5])
data[data.argmax()] = 0
data

array([5, 4, 4, 3, 3, 3, 2, 2, 1, 0, 1, 2, 2, 3, 3, 3, 4, 4, 5])

Преобразовать массив из float в int

In [16]:
data = np.arange(5.).astype(int)
data

array([0, 1, 2, 3, 4])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [17]:
# Евклидова метрика
# Рассстояния представлены в виде матрицы
from scipy.spatial.distance import pdist, squareform, cdist

coordinates = np.random.randint(0, 10, size=10*2).reshape((10, 2))
distance = cdist(coordinates, coordinates)

Случайно расположить p элементов в 2D массив

In [18]:
n = 5
p = 3
data = np.ones((n,n))
np.put(data, np.random.choice(n*n, p, replace=False), 100)
data

array([[  1.,   1.,   1.,   1.,   1.],
       [100.,   1.,   1., 100.,   1.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1., 100.],
       [  1.,   1.,   1.,   1.,   1.]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [19]:
data = np.arange(1, 6)
print(data)

new_data = np.array([[elem]+[0]*3 for elem in data]).ravel()
print(new_data)

[1 2 3 4 5]
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


Найти наиболее частое значение в массиве

In [20]:
data = np.array([2, 2, 2, 5, 5, 1, 0, 1, 5, 5, 2, 2, 2])

values, counts = np.unique(data, return_counts=True)
print("Values:", values)
print("Counts:", counts)

index = counts.argmax()
print("Most common value: ", values[index])

Values: [0 1 2 5]
Counts: [1 2 6 4]
Most common value:  2


Найти n наибольших значений в массиве

In [21]:
n = 3
print("Most n common values:", ' '.join(str(values[index]) for index in counts.argsort()[::-1][:n]))

Most n common values: 2 5 1


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [22]:
import pandas as pd

In [23]:
food = pd.read_csv('data/en.openfoodfacts.org.products.tsv', sep='\t', low_memory=False)

Посмотреть первые 5 записей

In [24]:
food.head(5).T

0  \
code                                                                      0000000003087   
url                                   http://world-en.openfoodfacts.org/product/0000...   
creator                                                      openfoodfacts-contributors   
created_t                                                                    1474103866   
created_datetime                                                   2016-09-17T09:17:46Z   
last_modified_t                                                              1474103893   
last_modified_datetime                                             2016-09-17T09:18:13Z   
product_name                                                         Farine de blé noir   
generic_name                                                                        NaN   
quantity                                                                            1kg   
packaging                                                                           NaN   
packaging_tags                                                                      NaN   
brands                                                                  Ferme t'y R'nao   
brands_tags                                                             ferme-t-y-r-nao   
categories                                                                          NaN   
categories_tags                                                                     NaN   
categories_en                                                                       NaN   
origins                                                                             NaN   
origins_tags                                                                        NaN   
manufacturing_places                                                                NaN   
manufacturing_places_tags                                                           NaN   
labels                                                                              NaN   
labels_tags                                                                         NaN   
labels_en                                                                           NaN   
emb_codes                                                                           NaN   
emb_codes_tags                                                                      NaN   
first_packaging_code_geo                                                            NaN   
cities                                                                              NaN   
cities_tags                                                                         NaN   
purchase_places                                                                     NaN   
...                                                                                 ...   
pantothenic-acid_100g                                                               NaN   
silica_100g                                                                         NaN   
bicarbonate_100g                                                                    NaN   
potassium_100g                                                                      NaN   
chloride_100g                                                                       NaN   
calcium_100g                                                                        NaN   
phosphorus_100g                                                                     NaN   
iron_100g                                                                           NaN   
magnesium_100g                                                                      NaN   
zinc_100g                                                                           NaN   
copper_100g                                                                         NaN   
manganese_100g                                                                      NaN   
fluoride_100g                                                                     

Сколько наблюдений в наборе данных?


In [25]:
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [26]:
food.shape[1]

163

Напечатайте все названия столбцов

In [27]:
print(food.columns.values)

['code' 'url' 'creator' 'created_t' 'created_datetime' 'last_modified_t'
 'last_modified_datetime' 'product_name' 'generic_name' 'quantity'
 'packaging' 'packaging_tags' 'brands' 'brands_tags' 'categories'
 'categories_tags' 'categories_en' 'origins' 'origins_tags'
 'manufacturing_places' 'manufacturing_places_tags' 'labels' 'labels_tags'
 'labels_en' 'emb_codes' 'emb_codes_tags' 'first_packaging_code_geo'
 'cities' 'cities_tags' 'purchase_places' 'stores' 'countries'
 'countries_tags' 'countries_en' 'ingredients_text' 'allergens'
 'allergens_en' 'traces' 'traces_tags' 'traces_en' 'serving_size'
 'no_nutriments' 'additives_n' 'additives' 'additives_tags' 'additives_en'
 'ingredients_from_palm_oil_n' 'ingredients_from_palm_oil'
 'ingredients_from_palm_oil_tags'
 'ingredients_that_may_be_from_palm_oil_n'
 'ingredients_that_may_be_from_palm_oil'
 'ingredients_that_may_be_from_palm_oil_tags' 'nutrition_grade_uk'
 'nutrition_grade_fr' 'pnns_groups_1' 'pnns_groups_2' 'states'
 'states_tags' 

Какое название у 105 столбца?

In [28]:
food.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [30]:
food['-glucose_100g'].dtype

dtype('float64')

Как проиндексирован набор данных?

In [31]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [32]:
food['product_name'][18]

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [12]:
import pandas as pd
import numpy as np
chipo = pd.read_csv('data/chipotle.tsv', sep='\t')
chipo.head(10)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                NaN     $1.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

In [13]:
# В колонку item_price запишем цену за одну единицу товара
# item_price = item_price / quantity
chipo['item_price'] = chipo['item_price'].apply(lambda price: price[1:]).astype('float')
chipo['item_price'] = chipo['item_price']/chipo['quantity']

In [14]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null float64
dtypes: float64(1), int64(2), object(2)
memory usage: 180.6+ KB


In [15]:
# Таблица с названием и ценой продуктов
# Уникальность продукта определяется названием и описанием
menu_columns = ['item_name', 'choice_description', 'item_price']
chipo_menu = chipo.drop_duplicates(['item_name', 'choice_description'])[menu_columns]
print(chipo_menu.shape)

(1871, 3)


Как много продуктов стоят более чем $10.00?

In [16]:
len(chipo_menu[chipo_menu['item_price'] > 10])

707

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [17]:
chipo_menu.head(10)

item_name  \
0           Chips and Fresh Tomato Salsa   
1                                   Izze   
2                       Nantucket Nectar   
3  Chips and Tomatillo-Green Chili Salsa   
4                           Chicken Bowl   
5                           Chicken Bowl   
6                          Side of Chips   
7                          Steak Burrito   
8                       Steak Soft Tacos   
9                          Steak Burrito   

                                  choice_description  item_price  
0                                                NaN        2.39  
1                                       [Clementine]        3.39  
2                                            [Apple]        3.39  
3                                                NaN        2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...        8.49  
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...       10.98  
6                                                NaN        1.69  
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...       11.75  
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...        9.25  
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...        9.25

Отсортировать по имени предмета

In [18]:
chipo_menu = chipo_menu.sort_values(['item_name'])
chipo_menu.head(10)

item_name                                 choice_description  \
341   6 Pack Soft Drink                                        [Diet Coke]   
298   6 Pack Soft Drink                                           [Sprite]   
357   6 Pack Soft Drink                                             [Coke]   
721   6 Pack Soft Drink                                           [Nestea]   
3141  6 Pack Soft Drink                                         [Lemonade]   
127       Barbacoa Bowl  [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...   
1264      Barbacoa Bowl  [Tomatillo Red Chili Salsa, [Rice, Black Beans...   
3376      Barbacoa Bowl  [Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]   
3017      Barbacoa Bowl  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...   
2073      Barbacoa Bowl  [Tomatillo Green Chili Salsa, [Fajita Vegetabl...   

      item_price  
341         6.49  
298         6.49  
357         6.49  
721         6.49  
3141        6.49  
127         9.25  
1264        9.25  
3376        9.25  
3017       11.75  
2073       11.75

Сколько было заказано самого дорогого предмета?

In [8]:
# Так как разных предметов с самой высокой ценой несколько, 
# то посчитаем, сколько было заказано самых дорогих предметов за эту цену
top_price = chipo_menu.sort_values('item_price', ascending=False)['item_price'].values[0]
top_price

11.89

In [20]:
# Ответ
chipo[chipo['item_price'] == top_price]['quantity'].sum()

30

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [21]:
# 1-ый способ
chipo.groupby(by='item_name')['quantity'].agg(np.sum)['Veggie Salad Bowl']

18

In [22]:
# 2-ой способ
chipo[chipo['item_name'] == 'Veggie Salad Bowl']['quantity'].sum()

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [23]:
filter_ = (chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)
chipo[filter_].shape[0]

20